# Generated by Django 3.2.16 on 2022-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='excerpt',
            field=models.TextField(default="Note's Excerpt", null=True),
        ),
        migrations.AlterField(
            model_name='core',
            name='title',
            field=models.CharField(default="Note's Title", max_length=200),
        ),
    ]
